name: Release

on:
  push:
    tags:
      - "v[0-9]+"

permissions:
  contents: read
  issues: write

jobs:
  tests:
    uses: ./.github/workflows/lintandtests.yml

  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get information
        id: tags
        run: |
          currentTag=${{ github.ref_name }}
          previousTag=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "currentTag=${currentTag}" >> $GITHUB_OUTPUT
          echo "previousTag=${previousTag}" >> $GITHUB_OUTPUT
          echo "author=${{ github.actor }}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%d.%m.%Y %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Build Changelog
        id: build_changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          github-token: ${{ github.token }}
          commit-types: |
            feat    : New Features
            fix     : Bug Fixes
            build   : Build System & Dependencies
            perf    : Performance Improvements
            docs    : Documentation
            test    : Tests
            refactor: Refactors
            chore   : Chores
            ci      : CI
            style   : Code Style
            revert  : Reverts
          default-commit-type: Other Changes
          mention-authors: true
          mention-new-contributors: false
          include-compare-link: true
          include-pr-links: true
          include-commit-links: true
          semver: false
          use-github-autolink: true

      - name: Create or update issue
        id: create_issue
        uses: JasonEtco/create-an-issue@v2
        env:
          VERSION: ${{ steps.tags.outputs.currentTag}}
          AUTHOR: ${{ steps.tags.outputs.author }}
          DATE: ${{ steps.tags.outputs.date }}
          CHANGELOG: ${{ steps.build_changelog.outputs.changelog }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/issue_template.md
          update_existing: true
          search_existing: all
    outputs:
      issueNumber: ${{ steps.create_issue.outputs.number }}
